FROM amazoncorretto:21-alpine-jdk
ARG JAR_FILE=build/libs/*.jar
ARG PROFILES
ARG ENV
ARG AWS_BUCKET
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG DB_HOST
ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG SECRET_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET

COPY ${JAR_FILE} app.jar
ENV PROFILES=${PROFILES} ENV=${ENV} AWS_BUCKET=${AWS_BUCKET} AWS_ACCESS_KEY=${AWS_ACCESS_KEY} AWS_SECRET_KEY=${AWS_SECRET_KEY} DB_HOST=${DB_HOST} DB_NAME=${DB_NAME} DB_USERNAME=${DB_USERNAME} DB_PASSWORD=${DB_PASSWORD} SECRET_KEY=${SECRET_KEY} GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}  GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-Dserver.env=${ENV}", "-jar", "app.jar"]